In [1]:
import numpy as np
import pandas as pd

In [2]:
# read file train
train = pd.read_csv("train.csv")
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
# read file test
test = pd.read_csv("test.csv")
test.tail()

PassengerId  Pclass                          Name     Sex   Age  SibSp  \
413         1305       3            Spector, Mr. Woolf    male   NaN      0   
414         1306       1  Oliva y Ocana, Dona. Fermina  female  39.0      0   
415         1307       3  Saether, Mr. Simon Sivertsen    male  38.5      0   
416         1308       3           Ware, Mr. Frederick    male   NaN      0   
417         1309       3      Peter, Master. Michael J    male   NaN      1   

     Parch              Ticket      Fare Cabin Embarked  
413      0           A.5. 3236    8.0500   NaN        S  
414      0            PC 17758  108.9000  C105        C  
415      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416      0              359309    8.0500   NaN        S  
417      1                2668   22.3583   NaN        C

In [4]:
# fill missing value by median (numeric feature)
train["Age"] = train["Age"].fillna(train["Age"].median())
test["Age"] = test["Age"].fillna(train["Age"].median())

In [5]:
# convert feature from category to numeric
train.loc[train["Embarked"] == 'S', "Embarked"] = 0.0
train.loc[train["Embarked"] == 'C', "Embarked"] = 1.0
train.loc[train["Embarked"] == 'Q', "Embarked"] = 2.0
train.loc[train["Sex"] == 'male', "Sex"] = 0.0
train.loc[train["Sex"] == 'female', "Sex"] = 1.0
test.loc[test["Embarked"] == 'S', "Embarked"] = 0.0
test.loc[test["Embarked"] == 'C', "Embarked"] = 1.0
test.loc[test["Embarked"] == 'Q', "Embarked"] = 2.0
test.loc[test["Sex"] == 'male', "Sex"] = 0.0
test.loc[test["Sex"] == 'female', "Sex"] = 1.0

In [6]:
# drop missing value (category feature)
train.dropna(subset=['Embarked'], inplace=True)
test.dropna(subset=['Embarked'], inplace=True)

In [7]:
# set input feature and target
x_train = np.array(train[["Pclass", "Sex", "Age", "Embarked"]].values, dtype=float)
y_train = np.array(train["Survived"].values, dtype=float)
x_test = np.array(test[["Pclass", "Sex", "Age", "Embarked"]].values, dtype=float)

In [16]:
from Regression.LogisticRegression import LogisticRegression

# train logistic regression
model=LogisticRegression()
theta,bias,_=model.train(x_train,y_train,10000,0.00001,889)

epoch 0
loss 1.2262277638434913
---------------
epoch 1
loss 1.0618842603729501
---------------
epoch 2
loss 1.0493066820278225
---------------
epoch 3
loss 1.0466455946773092
---------------
epoch 4
loss 1.0439989675527954
---------------
epoch 5
loss 1.041359451656016
---------------
epoch 6
loss 1.0387270171686802
---------------
epoch 7
loss 1.0361016818666942
---------------
epoch 8
loss 1.0334834637177146
---------------
epoch 9
loss 1.0308723805986586
---------------
epoch 10
loss 1.0282684502889639
---------------
epoch 11
loss 1.02567169046874
---------------
epoch 12
loss 1.0230821187166905
---------------
epoch 13
loss 1.0204997525080464
---------------
epoch 14
loss 1.0179246092124856
---------------
epoch 15
loss 1.0153567060920474
---------------
epoch 16
loss 1.0127960602990327
---------------
epoch 17
loss 1.0102426888739011
---------------
epoch 18
loss 1.0076966087431558
---------------
epoch 19
loss 1.0051578367172214
---------------
epoch 20
loss 1.002626389488315
-

In [17]:
# weight of logistic regression
theta,bias

(array([-0.98168762,  2.49672278, -0.02262808,  0.33296665]),
 array([1.26148227]))

In [19]:
# probability of test set
model.probability(x_test)

array([0.14205617, 0.43773057, 0.19171565, 0.09157627, 0.57818436,
       0.11916369, 0.69002434, 0.21581506, 0.67673414, 0.10351451,
       0.08971115, 0.31840814, 0.90517297, 0.10645617, 0.84722469,
       0.8298723 , 0.3040803 , 0.13873894, 0.55037452, 0.53191785,
       0.34710633, 0.13156025, 0.89500637, 0.53433876, 0.88322554,
       0.05651979, 0.93160864, 0.13473269, 0.34345015, 0.12087181,
       0.13784598, 0.22357261, 0.51659778, 0.54476877, 0.48348573,
       0.14563768, 0.54476877, 0.58369308, 0.09541136, 0.08971115,
       0.09681643, 0.41246327, 0.06841267, 0.75324366, 0.85299083,
       0.09541136, 0.39999107, 0.1609423 , 0.8521796 , 0.49963283,
       0.43455776, 0.2729147 , 0.7928627 , 0.89500637, 0.26844771,
       0.22375298, 0.07758913, 0.09541136, 0.08971115, 0.90845155,
       0.11222048, 0.19372402, 0.10998581, 0.7273577 , 0.57898211,
       0.7615586 , 0.74493338, 0.31351759, 0.47783724, 0.80515534,
       0.71829128, 0.10351451, 0.53915165, 0.49196594, 0.91031

In [20]:
# predict test set
# probability >= 0.5 -> predict 1
# probability < 0.5  -> predict 0
model.predict(x_test,0.5)

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,